// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	globals: {
		placeholders: {
			/**
			 * E​m​a​i​l
			 */
			email: string
			/**
			 * P​a​s​s​w​o​r​d
			 */
			password: string
			/**
			 * E​n​t​e​r​ ​P​a​s​s​w​o​r​d
			 */
			enter_password: string
			/**
			 * C​o​n​f​i​r​m​ ​P​a​s​s​w​o​r​d
			 */
			confirm_password: string
			/**
			 * Y​o​u​r​ ​n​a​m​e
			 */
			your_name: string
			/**
			 * Y​o​u​r​ ​e​m​a​i​l
			 */
			your_email: string
			/**
			 * Y​o​u​r​ ​p​a​s​s​w​o​r​d
			 */
			your_password: string
			/**
			 * Y​o​u​r​ ​c​o​d​e
			 */
			your_code: string
			/**
			 * F​i​r​s​t​ ​A​p​p​w​r​i​t​e​ ​P​r​o​j​e​c​t
			 */
			first_appwrite_project: string
		}
		/**
		 * U​p​d​a​t​e
		 */
		update: string
		/**
		 * R​e​c​o​v​e​r
		 */
		recover: string
		/**
		 * A​c​c​e​p​t
		 */
		accept: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
	}
	login: {
		/**
		 * S​i​g​n​ ​i​n
		 */
		title: string
		field_inputs: {
			/**
			 * E​m​a​i​l
			 */
			email: string
			/**
			 * P​a​s​s​w​o​r​d
			 */
			password: string
		}
	}
	sign_up: {
		/**
		 * S​i​g​n​ ​u​p
		 */
		title: string
		field_inputs: {
			/**
			 * N​a​m​e
			 */
			name: string
			/**
			 * E​m​a​i​l
			 */
			email: string
			/**
			 * P​a​s​s​w​o​r​d
			 */
			password: string
			/**
			 * c​o​d​e
			 */
			code: string
		}
		/**
		 * A​l​r​e​a​d​y​ ​g​o​t​ ​a​n​ ​a​c​c​o​u​n​t​?
		 */
		already_registered: string
	}
	password_recovery: {
		/**
		 * P​a​s​s​w​o​r​d​ ​R​e​c​o​v​e​r​y
		 */
		title: string
		/**
		 * F​o​r​g​o​t​ ​P​a​s​s​w​o​r​d
		 */
		forgot_password: string
		field_inputs: {
			/**
			 * E​m​a​i​l
			 */
			email: string
			/**
			 * N​e​w​ ​p​a​s​s​w​o​r​d
			 */
			new_password: string
			/**
			 * C​o​n​f​i​r​m​ ​p​a​s​s​w​o​r​d
			 */
			cnf_password: string
		}
	}
	accept_invite: {
		/**
		 * A​c​c​e​p​t​ ​i​n​v​i​t​e
		 */
		title: string
		/**
		 * I​n​v​a​l​i​d​ ​i​n​v​i​t​e
		 */
		invalid_invite: string
		/**
		 * I​n​v​i​t​e
		 */
		invite: string
		/**
		 * S​i​g​n​ ​u​p​ ​t​o​ ​A​p​p​w​r​i​t​e
		 */
		sign_up: string
		warning_alert: {
			/**
			 * T​h​e​ ​i​n​v​i​t​e​ ​l​i​n​k​ ​i​s​ ​n​o​t​ ​v​a​l​i​d
			 */
			title: string
			/**
			 * P​l​e​a​s​e​ ​a​s​k​ ​t​h​e​ ​p​r​o​j​e​c​t​ ​o​w​n​e​r​ ​t​o​ ​s​e​n​d​ ​y​o​u​ ​a​ ​n​e​w​ ​i​n​v​i​t​e​.
			 */
			sub_title: string
		}
		success_alert: {
			/**
			 * Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​i​n​v​i​t​e​d​ ​t​o​ ​j​o​i​n​ ​a​ ​t​e​a​m​ ​p​r​o​j​e​c​t​ ​o​n​ ​A​p​p​w​r​i​t​e
			 */
			title: string
		}
	}
	privacy_and_policy: {
		/**
		 * B​y​ ​a​c​c​e​p​t​i​n​g​ ​t​h​e​ ​i​n​v​i​t​a​t​i​o​n​,​ ​y​o​u​ ​a​g​r​e​e​ ​t​o​ ​t​h​e
		 */
		main_text: string
		/**
		 * T​e​r​m​s​ ​a​n​d​ ​C​o​n​d​i​t​i​o​n​s
		 */
		terms_and_condition: string
		/**
		 * a​n​d
		 */
		and: string
		/**
		 * P​r​i​v​a​c​y​ ​a​n​d​ ​P​o​l​i​c​y
		 */
		privacy_policy: string
	}
	console: {
		onboarding: {
			/**
			 * O​n​b​o​a​r​d​i​n​g
			 */
			header: string
			/**
			 * L​e​t​'​s​ ​c​r​e​a​t​e​ ​y​o​u​r​ ​f​i​r​s​t​ ​p​r​o​j​e​c​t
			 */
			title: string
		}
		basic_keywords: {
			/**
			 * P​r​o​j​e​c​t
			 */
			project: string
			/**
			 * P​r​o​j​e​c​t​ ​n​a​m​e
			 */
			project_name: string
			/**
			 * P​r​o​j​e​c​t​ ​I​D
			 */
			project_id: string
			/**
			 * C​r​e​a​t​e​ ​P​r​o​j​e​c​t
			 */
			create_project: string
		}
	}
}

export type TranslationFunctions = {
	globals: {
		placeholders: {
			/**
			 * Email
			 */
			email: () => LocalizedString
			/**
			 * Password
			 */
			password: () => LocalizedString
			/**
			 * Enter Password
			 */
			enter_password: () => LocalizedString
			/**
			 * Confirm Password
			 */
			confirm_password: () => LocalizedString
			/**
			 * Your name
			 */
			your_name: () => LocalizedString
			/**
			 * Your email
			 */
			your_email: () => LocalizedString
			/**
			 * Your password
			 */
			your_password: () => LocalizedString
			/**
			 * Your code
			 */
			your_code: () => LocalizedString
			/**
			 * First Appwrite Project
			 */
			first_appwrite_project: () => LocalizedString
		}
		/**
		 * Update
		 */
		update: () => LocalizedString
		/**
		 * Recover
		 */
		recover: () => LocalizedString
		/**
		 * Accept
		 */
		accept: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
	}
	login: {
		/**
		 * Sign in
		 */
		title: () => LocalizedString
		field_inputs: {
			/**
			 * Email
			 */
			email: () => LocalizedString
			/**
			 * Password
			 */
			password: () => LocalizedString
		}
	}
	sign_up: {
		/**
		 * Sign up
		 */
		title: () => LocalizedString
		field_inputs: {
			/**
			 * Name
			 */
			name: () => LocalizedString
			/**
			 * Email
			 */
			email: () => LocalizedString
			/**
			 * Password
			 */
			password: () => LocalizedString
			/**
			 * code
			 */
			code: () => LocalizedString
		}
		/**
		 * Already got an account?
		 */
		already_registered: () => LocalizedString
	}
	password_recovery: {
		/**
		 * Password Recovery
		 */
		title: () => LocalizedString
		/**
		 * Forgot Password
		 */
		forgot_password: () => LocalizedString
		field_inputs: {
			/**
			 * Email
			 */
			email: () => LocalizedString
			/**
			 * New password
			 */
			new_password: () => LocalizedString
			/**
			 * Confirm password
			 */
			cnf_password: () => LocalizedString
		}
	}
	accept_invite: {
		/**
		 * Accept invite
		 */
		title: () => LocalizedString
		/**
		 * Invalid invite
		 */
		invalid_invite: () => LocalizedString
		/**
		 * Invite
		 */
		invite: () => LocalizedString
		/**
		 * Sign up to Appwrite
		 */
		sign_up: () => LocalizedString
		warning_alert: {
			/**
			 * The invite link is not valid
			 */
			title: () => LocalizedString
			/**
			 * Please ask the project owner to send you a new invite.
			 */
			sub_title: () => LocalizedString
		}
		success_alert: {
			/**
			 * You have been invited to join a team project on Appwrite
			 */
			title: () => LocalizedString
		}
	}
	privacy_and_policy: {
		/**
		 * By accepting the invitation, you agree to the
		 */
		main_text: () => LocalizedString
		/**
		 * Terms and Conditions
		 */
		terms_and_condition: () => LocalizedString
		/**
		 * and
		 */
		and: () => LocalizedString
		/**
		 * Privacy and Policy
		 */
		privacy_policy: () => LocalizedString
	}
	console: {
		onboarding: {
			/**
			 * Onboarding
			 */
			header: () => LocalizedString
			/**
			 * Let's create your first project
			 */
			title: () => LocalizedString
		}
		basic_keywords: {
			/**
			 * Project
			 */
			project: () => LocalizedString
			/**
			 * Project name
			 */
			project_name: () => LocalizedString
			/**
			 * Project ID
			 */
			project_id: () => LocalizedString
			/**
			 * Create Project
			 */
			create_project: () => LocalizedString
		}
	}
}

export type Formatters = {}
