<script lang="ts">
    import { invalidate } from '$app/navigation';
    import { Submit, trackError, trackEvent } from '$lib/actions/analytics';
    import { Modal, CopyInput } from '$lib/components';
    import { Dependencies } from '$lib/constants';
    import { Button, InputDigits } from '$lib/elements/forms';
    import { sdk } from '$lib/stores/sdk';
    import { AuthenticatorType, type Models } from '@appwrite.io/console';
    import QrFrame from '$lib/images/qr2.svg';
    import { addNotification } from '$lib/stores/notifications';

    export let showSetup = false;

    let code: string;
    let type: Models.MfaType = null;
    let step = 1;
    let error = '';

    async function addAuthenticator(): Promise<string> {
        type = await sdk.forConsole.account.createMfaAuthenticator(AuthenticatorType.Totp);
        trackEvent(Submit.AccountAuthenticatorCreate);

        return sdk.forConsole.avatars.getQR(type.uri, 192 * 2);
    }

    async function verifyAuthenticator() {
        try {
            await sdk.forConsole.account.updateMfaAuthenticator(AuthenticatorType.Totp, code);
            await Promise.all([invalidate(Dependencies.ACCOUNT), invalidate(Dependencies.FACTORS)]);
            showSetup = false;
            addNotification({
                type: 'success',
                message: 'Authenticator app connected successfully'
            });
            trackEvent(Submit.AccountAuthenticatorUpdate);
        } catch (e) {
            error = e.message;
            trackError(e, Submit.AccountAuthenticatorUpdate);
        }
    }
</script>

<Modal
    title={step === 1 ? 'Scan QR code' : 'Enter verification code'}
    bind:show={showSetup}
    onSubmit={verifyAuthenticator}
    {error}>
    {#key showSetup}
        {#if step === 1}
            <p>
                Install an authenticator app on your mobile device, open it and scan the provided QR
                code or enter it manually.
            </p>
            {#await addAuthenticator()}
                <div class="loading">
                    <div class="loader"></div>
                </div>
            {:then qr}
                <div
                    class="qr"
                    style:background-image={`url(${QrFrame})`}
                    style:background-repeat="no-repeat"
                    style:background-position="center"
                    style:background-size="contain">
                    <img alt="MFA QR Code" class="code" src={qr} />
                </div>
                <span class="with-separators eyebrow-heading-3">or</span>

                <div>
                    <CopyInput
                        label="Manual entry code"
                        optionalText="Manually enter the following code into the authenticator app"
                        value={type.secret} />
                </div>
            {/await}
        {:else}
            <label for="code">Enter the 6-digit one-time code generated by the app</label>
            <InputDigits bind:value={code} autofocus />
        {/if}
    {/key}
    <svelte:fragment slot="footer">
        <Button text on:click={() => (showSetup = false)}>Cancel</Button>
        {#if step === 1}
            <Button submit={false} on:click={() => (step = 2)}>Continue</Button>
        {:else}
            <Button submit>Continue</Button>
        {/if}
    </svelte:fragment>
</Modal>

<style lang="scss">
    .loading {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 351px;
    }
    .qr {
        width: 100%;
        height: 220px;
        display: flex;
        align-items: center;

        .code {
            width: 100%;
            max-width: 192px;
            aspect-ratio: 1;
            margin: 0 auto;
            display: block;
        }
    }
</style>
