# Use the Bun image as the base image
FROM daytonaio/sandbox:0.4.3

# Set the working directory in the container
WORKDIR /home/daytona/workspace

RUN npm -v 
RUN npm install -g bun
RUN bunx giget --version

EXPOSE 3000

ENTRYPOINT ["sleep", "infinity"]