#!/bin/sh

# Regenerate env.js from runtime PUBLIC_ environment variables

echo "Regenerating env.js from environment variables..."

# Build JSON object from PUBLIC_ env vars
env_json="{"
first=true

for var in $(printenv | grep '^PUBLIC_' | awk -F= '{print $1}' | sort); do
    value=$(printenv "$var")
    
    # Escape special characters for JSON
    escaped_value=$(echo "$value" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')
    
    if [ "$first" = true ]; then
        first=false
    else
        env_json="$env_json,"
    fi
    
    env_json="$env_json\"$var\":\"$escaped_value\""
    echo "  $var=$value"
done

env_json="$env_json}"

# Write to env.js
# Use CONSOLE_BUILD_PATH env var if set, otherwise try common locations
if [ -n "$CONSOLE_BUILD_PATH" ]; then
    env_file="$CONSOLE_BUILD_PATH/_app/env.js"
elif [ -f "/usr/share/nginx/html/console/_app/env.js" ]; then
    env_file="/usr/share/nginx/html/console/_app/env.js"
elif [ -f "./build/_app/env.js" ]; then
    env_file="./build/_app/env.js"
elif [ -f "./_app/env.js" ]; then
    env_file="./_app/env.js"
else
    echo "⚠ Error: Cannot find env.js file. Set CONSOLE_BUILD_PATH env var to the build directory."
    exit 1
fi

echo "export const env=$env_json" > "$env_file"

echo "✓ Generated $env_file"

# Remove compressed versions (they'll be regenerated by nginx if needed)
rm -f "${env_file}.br" "${env_file}.gz"

exec "$@"