<script lang="ts">
    import { invalidate } from '$app/navigation';
    import { Submit, trackEvent, trackError } from '$lib/actions/analytics';
    import { Modal } from '$lib/components';
    import { Dependencies } from '$lib/constants';
    import { Button } from '$lib/elements/forms';
    import { addNotification } from '$lib/stores/notifications';
    import { sdk } from '$lib/stores/sdk';

    export let showDelete = false;

    let code: string;

    async function deleteProvider() {
        try {
            await sdk.forConsole.account.deleteAuthenticator('totp', code);
            await invalidate(Dependencies.ACCOUNT);
            showDelete = false;
            addNotification({
                type: 'success',
                message: 'The authenticator has been removed'
            });
            trackEvent(Submit.AccountDelete);
        } catch (error) {
            addNotification({
                type: 'error',
                message: error.message
            });
            trackError(error, Submit.AccountDelete);
        }
    }
</script>

<Modal
    title="Delete authentication provider"
    bind:show={showDelete}
    onSubmit={deleteProvider}
    icon="exclamation"
    state="warning"
    headerDivider={false}>
    <p>Are you sure you want to delete this authentication method from your account?</p>
    <div>
        <label for="code">Enter the 6-digit one-time code generated by the app</label>
        <input
            required
            bind:value={code}
            id="code"
            class="u-margin-block-start-12"
            type="text"
            placeholder="Enter code"
            minlength="6"
            maxlength="6" />
    </div>
    <svelte:fragment slot="footer">
        <Button text on:click={() => (showDelete = false)}>Cancel</Button>
        <Button secondary submit>Delete</Button>
    </svelte:fragment>
</Modal>
