<script lang="ts">
    import { invalidate } from '$app/navigation';
    import { Submit, trackError } from '$lib/actions/analytics';
    import { Modal, Output, Copy, Alert } from '$lib/components';
    import LoadingDots from '$lib/components/loadingDots.svelte';
    import { Dependencies } from '$lib/constants';
    import { Button, FormList, InputDigits } from '$lib/elements/forms';
    import { Table, TableBody, TableCell, TableRow } from '$lib/elements/table';
    import { addNotification } from '$lib/stores/notifications';
    import { sdk } from '$lib/stores/sdk';
    import { AuthenticatorType, type Models } from '@appwrite.io/console';

    export let showSetup = false;
    export let showRecoveryCodes = false;

    let code: string;
    let type: Models.MfaType = null;
    async function addAuthenticator(): Promise<URL> {
        type = await sdk.forConsole.account.addAuthenticator(AuthenticatorType.Totp);

        return sdk.forConsole.avatars.getQR(type.uri, 192 * 2);
    }

    async function verifyAuthenticator() {
        try {
            await sdk.forConsole.account.verifyAuthenticator(AuthenticatorType.Totp, code);
            await invalidate(Dependencies.ACCOUNT);
            await invalidate(Dependencies.FACTORS);
            showSetup = false;
            showRecoveryCodes = true;
        } catch (error) {
            addNotification({
                type: 'error',
                message: error.message
            });
            trackError(error, Submit.AccountDelete);
        }
    }
</script>

<Modal
    title="Scan QR code"
    description="Open your authentication app and scan the QR code."
    bind:show={showSetup}
    onSubmit={verifyAuthenticator}>
    {#key showSetup}
        <p>
            Install an authenticator app on your mobile device, open it and scan the provided QR
            code or enter it manually.
        </p>
        <div class="qr">
            {#await addAuthenticator()}
                <LoadingDots />
            {:then qr}
                <img alt="MFA QR Code" class="code" src={qr.toString()} />
            {/await}
        </div>
        <hr />
        <FormList>
            <label for="code">Enter the 6-digit one-time code generated by the app</label>
            <InputDigits bind:value={code} autofocus />
        </FormList>
    {/key}
    <svelte:fragment slot="footer">
        <Button text on:click={() => (showSetup = false)}>Cancel</Button>
        <Button submit>Continue</Button>
    </svelte:fragment>
</Modal>

<Modal
    title="Save recovery codes"
    description="Learn more about multi-factor authentication in our documentation."
    bind:show={showRecoveryCodes}
    onSubmit={verifyAuthenticator}>
    {#if type}
        {@const formattedBackupCodes = type.backups.join('\n')}
        <Alert type="info">
            <span slot="title">
                It is highly recommended to securely store your recovery codes
            </span>
            <p>
                Use security codes for emergency sign-ins in case you've lost access to your mobile
                device. Each recovery code can only be used once, but you can re-generate a new set
                of 6 codes anytime.
            </p>
        </Alert>
        <div
            style:flex-direction="row-reverse"
            class="u-flex u-flex-vertical-mobile u-main-space-between u-gap-16">
            <ul class="buttons-list">
                <li class="buttons-list-item">
                    <Button
                        download="backups.txt"
                        href={`data:application/octet-stream;charset=utf-8,${formattedBackupCodes}`}
                        text>
                        <span class="icon-download" />
                        <span class="text">Download</span>
                    </Button>
                </li>
                <li class="buttons-list-item">
                    <Copy value={formattedBackupCodes} appendTo="parent">
                        <Button text>
                            <span class="icon-duplicate" />
                            <span class="text">Copy all</span>
                        </Button>
                    </Copy>
                </li>
            </ul>
        </div>
        <Table noMargin noStyles>
            <TableBody>
                {#each type.backups as code}
                    <TableRow>
                        <TableCell title="code">
                            <Output value={code} hideCopyIcon>{code}</Output>
                        </TableCell>
                        <TableCell title="actions" width={24}>
                            <Copy value={code} appendTo="parent">
                                <span class="icon-duplicate" aria-hidden="true" />
                            </Copy>
                        </TableCell>
                    </TableRow>
                {/each}
            </TableBody>
        </Table>
    {/if}
    <svelte:fragment slot="footer">
        <Button secondary on:click={() => (showRecoveryCodes = false)}>Close</Button>
    </svelte:fragment>
</Modal>

<style lang="scss">
    .qr {
        width: 100%;
        height: 220px;
        display: flex;
        align-items: center;

        .code {
            width: 100%;
            max-width: 192px;
            aspect-ratio: 1;
            margin: 0 auto;
            display: block;
        }
    }

    hr {
        height: 1px;
        width: calc(100% + 2rem);
        background-color: hsl(var(--color-border));

        margin-block-start: 1rem;
        margin-inline: -1rem;
    }
</style>
