<script lang="ts">
    import { Modal } from '$lib/components';
    import { Button, FormList, InputDigits } from '$lib/elements/forms';
    import { sdk } from '$lib/stores/sdk';
    import { AuthenticationFactor } from '@appwrite.io/console';

    export let show = false;
    export let regenerateRecoveryCodes: () => Promise<void>;

    let code = '';
    let error = '';

    async function verify() {
        try {
            const challenge = await sdk.forConsole.account.createMfaChallenge(
                AuthenticationFactor.Totp
            );
            await sdk.forConsole.account.updateMfaChallenge(challenge.$id, code);
            show = false;
            regenerateRecoveryCodes();
        } catch (e) {
            error = e.message;
        }
    }
</script>

<Modal
    title="Regenerate recovery codes"
    icon="exclamation"
    state="warning"
    headerDivider={false}
    {error}
    onSubmit={verify}
    bind:show>
    <p>
        Are you sure you want to regenerate all recovery codes? All <b
            >previously generated recovery codes will become invalid.</b>
    </p>
    <p>Enter the 6-digit verification code generated by your authenticator app to continue.</p>
    <FormList>
        <InputDigits bind:value={code} required autofocus autoSubmit={false} />
    </FormList>

    <svelte:fragment slot="footer">
        <Button text on:click={() => (show = false)}>Cancel</Button>
        <Button secondary submit>Regenerate</Button>
    </svelte:fragment>
</Modal>
