name: Dockerize Profiles

on:
    push:
        branches: [feat-profiles]
    pull_request:
        types: [opened, synchronize, reopened]
        branches: [feat-profiles]
    workflow_dispatch:

jobs:
    dockerize-profiles:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repo
              uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
            - name: Set up QEMU
              uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0
            - name: Log in to Docker Hub
              uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
              with:
                  images: appwrite/console-profiles
                  tags: |
                      type=ref,event=branch,prefix=branch-
                      type=ref,event=pr
                      type=sha,prefix=sha-
                      type=raw,value=gh-${{ github.run_id}}
                  flavor: |
                      latest=false

            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
              with:
                  context: .
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
