name: Tests

on:
    pull_request:
        branches: ['**']
        paths-ignore:
            - '**/*.md'
            - 'static/**/*'

env:
    PUBLIC_APPWRITE_ENDPOINT: http://appwrite.test/v1

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - name: Setup Bun
              uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
              with:
                  bun-version: 1.3.8

            - name: Audit dependencies
              run: bun audit --audit-level high

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Svelte Diagnostics
              run: bun check

            - name: Linter
              run: bun lint

            - name: Unit Tests
              run: bun test:unit

            - name: Build Console
              run: bun run build
